name: Unit Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python -m unittest
